FROM httpd:2.4.62

COPY entrypoint.sh /opt
COPY httpd.conf /usr/local/apache2/conf/
COPY test.lua  /usr/local/apache2

# RUN sed -i "s#deb.debian.org/debian#archive.debian.org/debian-archive#g" /etc/apt/sources.list.d/*
# RUN sed -i "s#deb.debian.org/debian#archive.debian.org/debian-archive#g" /etc/apt/sources.list

RUN apt update && apt install -y ncat procps

ENTRYPOINT /opt/entrypoint.sh